Tests Data for Auxilliary Db and Sqlite tables
dcrlabs/bug-free-happiness pull request #2
Opened 2019-03-18 18:52 UTC by dmigwi

2019-03-18 21:50 UTC, dmigwi commented on pgdb/queries.md
> +    CREATE TABLE test_addresses AS SELECT * FROM addresses WHERE block_time > '2019-02-17 03:23:23+03' LIMIT 200;
The **WHERE** condition(s) and **LIMIT** value can be changed to ones preference.
The custom scanner that reads the generated *.sql dump, drops the **test_** prefix from the tables automatically

2019-03-19 02:18 UTC, chappjc requested changes
Thanks for adding this in!

2019-03-19 02:18 UTC, chappjc commented on sqlitedb/queries.md
> +# The Sqlite db was generated from testnet data as below:
SQLite

2019-03-19 02:18 UTC, chappjc commented on sqlitedb/queries.md
> +- While in the sqlite shell create a dump file with the newly created tables's data.
While in the sqlite shell,[**<-comma**] create **dump files** with the newly created **tables'** data.

2019-03-19 02:18 UTC, chappjc commented on sqlitedb/queries.md
> +Dump data into  `data_1.sql` and `data_2.sql` as shown.
extra space before data_1

2019-03-19 02:18 UTC, chappjc commented on sqlitedb/queries.md
> +    cat data_1.sql data_2.sql >> sqlite_dump.sql
`>` instead of `>>`

2019-03-19 02:18 UTC, chappjc commented on pgdb/queries.md
> +    bug-free-happiness git:(master) ✗ pg_dump -t test_addresses -t test_agenda_votes -t test_agendas -t \
I'd replace `bug-free-happiness git:(master) ✗` with just `$ `.

2019-03-19 02:18 UTC, chappjc commented on pgdb/queries.md
> +            -t test_vins -t test_tickets --no-comments --column-inserts -U postgres t_dcrdata > pgdb/pgsql_dump.sql;
omit trailing `;`

2019-03-26 22:22 UTC, chappjc approved these changes

2019-03-26 22:23 UTC, merged