add meta table. add generator script for pgdb
dcrlabs/bug-free-happiness pull request #4
Opened 2019-04-28 06:38 UTC by buck54321

2019-04-28 15:08 UTC, buck54321 commented
I don't do a lot of shell scripting, so definitely check out `generator.sh`.

2019-04-29 16:35 UTC, chappjc requested changes
Looks good, just some suggestions.

2019-04-29 16:35 UTC, chappjc commented on pgdb/generate.sh
> +TEMPLATE=`cat template.sql`
Seeing as we're using bash, this might as well be `TEMPLATE=$(<template.sql)` to avoid spawning cat.

2019-04-29 16:35 UTC, chappjc commented on pgdb/generate.sh
> +if [ "$1" == "" ] || [ "$2" == "" ] || [ "$3" == "" ]; then
Should be able to do `[ $# -lt 3 ]`

2019-04-29 16:35 UTC, chappjc commented on pgdb/generate.sh
> +tar -cJf "$OPFILE".tar.xz "$OPFILE".sql
`XZ_OPT=-9e tar ...` Is how I've done this previously to pull off a little extra compression.  If it's insignificant, no need to update anything though.

2019-04-29 16:35 UTC, chappjc commented on pgdb/generate.sh
> +zip "$OPFILE".zip "$OPFILE".sql
`zip -9 ...` for the same reason.

2019-04-29 16:35 UTC, chappjc commented on pgdb/generate.sh
> +SQL=`echo "$TEMPLATE" | sed "s/_COUNT/$COUNT/g"`
A feature of ksh, bash, and zsh is the "here string":

```bash
SQL=`sed "s/_COUNT/$COUNT/g" <<< "$SQL"`
```

2019-04-29 20:51 UTC, chappjc approved these changes

2019-04-29 20:51 UTC, merged